### ISSUE TITLE
Fractals

### ISSUE THREAD

**Issue by Bachstelze** [mmirman/MentisOculi#1]
Do you think it is possible to add fractal calculations like in https://bananaft.itch.io/yedomaglobula ?
video example: https://www.youtube.com/watch?v=N1oKIbDqo8g&app=desktop

**Comment by mmirman** [comment]
oh yes, it is certainly possible - you construct the formula based on a level set and can use newton's method (aided by derivatives even!) to do ray-marching.  However, I don't have much time to add it (this project was tangential to my thesis work).  I'd be happy to provide any help I can if you want to pursue such an addition.

**Comment by Bachstelze** [comment]
Oh ja wunderbar! An was für einer Thesis arbeitest du?
I am going to integrate a new gpu and hope that it supports pytorch. With which version have you developed it?

**Comment by mmirman** [comment]
I'm working on adversarial examples for neural networks.  

This works (at least) for any GPU which supports CUDA 9.  Mainly, I think all NVIDIA GPUs from 2014 or later will support it.

**Comment by Bachstelze** [comment]
Oo nice!
Did you try a GAN for machine translation?
