### ISSUE TITLE
Red Artefacts

### ISSUE THREAD

**Issue by Bachstelze** [mmirman/MentisOculi#3]
Do you know what is the reason for the red artifacts? 
Perhaps some rays are trapped in the ring?!

**Comment by mmirman** [comment]
The integration algorithm used is ERPT which is known to (when using unbiased flow rules) cause artifacts.  In particular, the ring's material is partially red diffuse, and it is likely that there are some rays which achieve high luminance through a reflect-diffuse-reflect-diffuse combination, which while very unlikely to ever trigger with the used stop-probabilities, can happen.  In this case it would record red, and assign it an extremely high multiply.  More samples would likely remove this artifact, as would langevin MCMC
